version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "54867:54867"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - hyperflux-network

  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "npm install --no-fund --no-audit --loglevel=error && node server.js"
    ports:
      - "57273:54867"
    depends_on:
      - node
    networks:
      - hyperflux-network

networks:
  hyperflux-network:
    driver: bridge